--EJERCICIO 1
SELECT CIUDAD, TELEFONO
FROM OFICINAS
WHERE UPPER(CIUDAD) = 'EEUU'
ORDER BY CIUDAD;

--EJERCICIO 2
SELECT CODIGOOFICINA, CIUDAD, REGION, PAIS
FROM OFICINAS
WHERE UPPER(PAIS) LIKE ('E%');

--EJERCICIO 3
SELECT DISTINCT ESTADO
FROM PEDIDOS;

--EJERCICIO 4
SELECT NOMBRE, APELLIDO1||APELLIDO2, PUESTO
FROM EMPLEADOS
WHERE ;

--EJERCICIO 5
SELECT NOMBRECLIENTE, CIUDAD
FROM CLIENTES
WHERE UPPER(CIUDAD) NOT EXISTS (SELECT CIUDAD
								FROM OFICINAS);

--EJERCICIO 6 
SELECT INITCAP(C.NOMBRECLIENTE) AS "NOMBRE DE LOS CLIENTES", DP.CANTIDAD
FROM CLIENTES C, PEDIDOS P, DETALLEPEDIDOS DP
WHERE C.CODIGOCLIENTE = P.CODIGOCLIENTE
AND P.CODIGOPEDIDO = DP.CODIGOPEDIDO
AND DP.CANTIDAD > 200;

--EJERCICIO 7
SELECT C.NOMBRECLIENTE, E.NOMBRE||', '||E.APELLIDO1|| ' '||E.APELLIDO2 AS "REPRESENTANTE"
FROM CLIENTES C, EMPLEADOS E
WHERE C.CODIGOEMPLEADOREPVENTAS = E.CODIGOEMPLEADO;

--EJERCICIO 8
SELECT C.NOMBRECLIENTE, E.NOMBRE AS "NOM. Representante"
FROM CLIENTES C, EMPLEADOS E, PEDIDOS P
WHERE C.CODIGOEMPLEADOREPVENTAS = E.CODIGOEMPLEADO
AND C.CODIGOCLIENTE = P.CODIGOCLIENTE
AND P.COMENTARIOS IS NULL;