/*
1. OBTENER APELLIDO Y OFICIO DE LOS EMPLEADOS QUE TIENE EL MISMO OFICIO 
Y EL MISMO DEPT_NO QUE DE INVESTIGACIÓN
*/
SELECT OFICIO
FROM EMPLE;
                
SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE OFICIO IN (SELECT OFICIO
                    FROM EMPLE
                    WHERE DEPT_NO=(SELECT DEPT_NO
                                    FROM DEPART
                                    WHERE UPPER(DNOMBRE)='INVESTIGACION'));
--OTRA FORMA                
SELECT DISTINCT E.OFICIO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
AND UPPER(DNOMBRE)= 'INVESTIGACION';

SELECT DEPT_NO
FROM EMPLE
WHERE UPPER(OFICIO) = 'INVESTIGACION';

/*
VISUALIZAR EL NºDEPARTAMENTO, EL OFICIO Y EL SALARIO DE 
LOS EMPLEADOS CON MAYOR SALARIO DE CADA DEPARTAMENTO
*/
SELECT DEPT_NO, OFICIO, SALARIO
FROM EMPLE E
WHERE SALARIO IN (SELECT MAX(SALARIO)
                    FROM EMPLE
                    GROUP BY(E.DEPT_NO));
                    
SELECT DEPT_NO, OFICIO, SALARIO, APELLIDO
FROM EMPLE E
WHERE SALARIO IN (SELECT MAX(SALARIO)
                    FROM EMPLE EM
                    WHERE E.DEPT_NO = EM.DEPT_NO
                    );                    
                   
/*ELIMINAR LOS DEPARTAMENTOS QUE TIENEN MENOS DE 2 EMPLEADOS*/

SELECT DEPT_NO
FROM DEPART;

SELECT COUNT(EMP_NO), DEPT_NO
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(*) <2;

DELETE FROM DEPART WHERE DEPT_NO NOT IN (SELECT DEPT_NO
                                        FROM EMPLE
                                        GROUP BY DEPT_NO
                                        HAVING COUNT(*) >=2);
                                        
ROLLBACK;         

/*AUMENTAR 5000 EL SALARIO A TODOS LOS EMPLEADOS CUYO DEPARTAMENTO NO ESTE 
EN MADRID*/
SELECT EMP_NO, SALARIO
FROM EMPLE
WHERE DEPT_NO IN(SELECT DEPT_NO
                FROM DEPART
                WHERE UPPER(LOC)!= 'MADRID');

UPDATE EMPLE SET SALARIO = (SALARIO + 5000)
WHERE DEPT_NO IN (SELECT DEPT_NO
                    FROM DEPART
                    WHERE UPPER(LOC)!='MADRID');

ROLLBACK;

SELECT EMP_NO, SALARIO
FROM EMPLE
WHERE DEPT_NO IN(SELECT DEPT_NO
                FROM DEPART
                WHERE UPPER(LOC)!= 'MADRID');

