--EJERCICIO 1
SELECT DEPT_NO , DNOMBRE 
FROM DEPART
WHERE EXISTS (SELECT 'X' 
                FROM EMPLE 
                WHERE COMISION_PCT IS NOT NULL 
                AND DEPART.DEPT_NO = EMPLE.DEPT_NO);

--COMPROBACIÓN 
SELECT EMP_NO, D.DEPT_NO, DNOMBRE, COMISION_PCT
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
ORDER BY DNOMBRE;

--EJERCICIO 2

SELECT DEPT_NO , DNOMBRE
FROM DEPART
WHERE DEPT_NO NOT IN (SELECT DEPT_NO 
                        FROM EMPLE 
                        WHERE COMISION_PCT IS NOT NULL);

SELECT DEPT_NO , DNOMBRE
FROM DEPART
WHERE DEPT_NO IN (SELECT DEPT_NO 
                        FROM EMPLE 
                        WHERE COMISION_PCT IS NULL);

--COMPROBACIÓN 

INSERT INTO EMPLE VALUES(2222,'ANTONIO','PRESI2',NULL,TO_DATE('19/02/1975' , 'DD/MM/YYYY'),9000,3,20);

--EJERCICIO 3

SELECT D.DEPT_NO , D.DNOMBRE , COUNT(E.EMP_NO)
FROM DEPART D , EMPLE E
WHERE D.DEPT_NO = E.DEPT_NO
GROUP BY D.DEPT_NO , D.DNOMBRE
HAVING COUNT(E.EMP_NO)=(SELECT MAX(COUNT(E.EMP_NO)) FROM EMPLE GROUP BY DEPT_NO);

--COMPROBACION

SELECT D.DEPT_NO , D.DNOMBRE , COUNT(E.EMP_NO)
FROM DEPART D , EMPLE E
WHERE D.DEPT_NO = E.DEPT_NO
GROUP BY D.DEPT_NO , D.DNOMBRE
ORDER BY COUNT(E.EMP_NO)DESC;

--EJERCICIO 4

SELECT D.DEPT_NO , D.DNOMBRE , P.PROGRAMADORES "PROGRAMADORES"
FROM DEPART D , EMPLE E , (SELECT COUNT(EMP_NO) "PROGRAMADORES" , DEPT_NO FROM EMPLE WHERE UPPER(OFICIO)='PROGRAMADOR' GROUP BY DEPT_NO) P
WHERE D.DEPT_NO = E.DEPT_NO AND D.DEPT_NO = P.DEPT_NO
GROUP BY D.DEPT_NO , D.DNOMBRE , P.PROGRAMADORES
HAVING PROGRAMADORES=MAX(P.PROGRAMADORES);

SELECT MAX(COUNT(EMP_NO)) FROM EMPLE WHERE UPPER(OFICIO)='PROGRAMADOR' GROUP BY DEPT_NO;

--EJERCICIO 5

SELECT DEPT_NO , DNOMBRE 
FROM DEPART;