--EJERCICIO 1
SELECT DEPT_NO , DNOMBRE 
FROM DEPART
WHERE EXISTS (SELECT 'X' 
                FROM EMPLE 
                WHERE COMISION_PCT IS NOT NULL 
                AND DEPART.DEPT_NO = EMPLE.DEPT_NO);

--COMPROBACIÓN 
SELECT EMP_NO, D.DEPT_NO, DNOMBRE, COMISION_PCT
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
ORDER BY DNOMBRE;

--EJERCICIO 2

SELECT DEPT_NO , DNOMBRE
FROM DEPART
WHERE DEPT_NO NOT IN (SELECT DEPT_NO 
                        FROM EMPLE 
                        WHERE COMISION_PCT IS NOT NULL);
--COMPROBACIÓN 
SELECT DEPT_NO , DNOMBRE
FROM DEPART
WHERE DEPT_NO IN (SELECT DEPT_NO 
                        FROM EMPLE 
                        WHERE COMISION_PCT IS NULL);

--EJERCICIO 3

SELECT D.DEPT_NO , D.DNOMBRE , COUNT(E.EMP_NO)
FROM DEPART D , EMPLE E
WHERE D.DEPT_NO = E.DEPT_NO
GROUP BY D.DEPT_NO , D.DNOMBRE
HAVING COUNT(E.EMP_NO)=(SELECT MAX(COUNT(E.EMP_NO)) 
                        FROM EMPLE 
                        GROUP BY EMP_NO);

--COMPROBACION

SELECT D.DEPT_NO , D.DNOMBRE , COUNT(E.EMP_NO)
FROM DEPART D , EMPLE E
WHERE D.DEPT_NO = E.DEPT_NO
GROUP BY D.DEPT_NO , D.DNOMBRE
ORDER BY COUNT(E.EMP_NO)DESC;

--EJERCICIO 4

SELECT DEPT_NO, COUNT(*)
FROM EMPLE
WHERE UPPER(OFICIO)= 'PROGRAMADOR'
GROUP BY DEPT_NO;

SELECT E.DEPT_NO, D.DNOMBRE
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO --JOIN
AND UPPER(E.OFICIO) = 'PROGRAMADOR'
GROUP BY E.DEPT_NO, D.DNOMBRE
HAVING COUNT(E.EMP_NO) = (SELECT MAX(COUNT(*))
                            FROM EMPLE
                            WHERE UPPER(OFICIO) = 'PROGRAMADOR'
                            ORDER BY DEPT_NO);

--EJERCICIO 5

SELECT MAX(SUM(SALARIO + NVL(COMISION_PCT,0))) PRESUPUESTO
FROM EMPLE
GROUP BY DEPT_NO;

SELECT E.DEPT_NO, D.DNOMBRE, SUM(E.SALARIO + NVL(E.COMISION_PCT,0)) PRESUPUESTO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
GROUP BY E.DEPT_NO, D.DNOMBRE
HAVING SUM(E.SALARIO + NVL(E.COMISION_PCT,0)) = (SELECT MAX(SUM(SALARIO + NVL(COMISION_PCT,0)))
                                                FROM EMPLE
                                                GROUP BY DEPT_NO)
;