--EJERCICIO 1
DESC DEPART

DESC USER_CONSTRAINTS
DESC USER_CONS_COLUMNS

SELECT USER_CONSTRAINTS.CONSTRAINT_NAME, USER_CONS_COLUMNS.COLUMN_NAME
FROM USER_CONSTRAINTS, USER_CONS_COLUMNS
WHERE USER_CONSTRAINTS.CONSTRAINT_NAME = USER_CONS_COLUMNS.CONSTRAINT_NAME 
AND UPPER(USER_CONSTRAINTS.TABLE_NAME)= 'DEPART';

DROP TABLE DEPARTSEQ;

CREATE TABLE DEPARTSEQ AS SELECT * FROM DEPART;

DESC DEPARTSEQ;

SELECT * FROM DEPARTSEQ;

--EJERCICIO 2
DROP SEQUENCE DEPT_ID_SEQ;

CREATE SEQUENCE DEPT_ID_SEQ
START WITH 200
MAXVALUE 1000
INCREMENT BY 10
NOCYCLE
NOCACHE;

DESC USER_SEQUENCES;

SELECT * FROM USER_SEQUENCES
WHERE UPPER(SEQUENCE_NAME)= 'DEPT_ID_SEQ';

--EJERCICIO 3
DESC USER_SEQUENCES
SELECT SEQUENCE_NAME, MAX_VALUE, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES;

--EJERCICIO 4
/*ESTA EN EL SCRIPT LAB9_4.SQL*/

--EJERCICIO 5
SELECT DEPT_ID_SEQ.NEXTVAL 
FROM DUAL;

--AÑADIR UN NUEVO DEPARTAMENTO CON LA SECUENCIA RECIÉN GENERADA 
INSERT INTO DEPARTSEQ (DEPT_NO, DNOMBRE)
VALUES (DEPT_ID_SEQ.CURRVAL, 'MOLANO');

SELECT * 
FROM DEPARTSEQ
WHERE UPPER(DNOMBRE)='MOLANO';

ROLLBACK;

--COMPROBACIÓN DEL ROLLBACK
SELECT * 
FROM DEPARTSEQ;

--EJERCICIO 6
DROP TABLE CENTRO CASCADE CONSTRAINTS;
CREATE TABLE CENTRO(
    ID NUMBER(2) GENERATED ALWAYS AS IDENTITY
                    START WITH 1
                    MINVALUE 1
                    MAXVALUE 99
                    INCREMENT BY 1
                    NOCYCLE NOCACHE,
    NOMBRE VARCHAR2(30) NOT NULL,
    CALLE VARCHAR2(30),
    NUMERO NUMBER(2),
    CP VARCHAR2(5),
    CIUDAD VARCHAR2(15),
    PROVINCIA VARCHAR2(40),
    TELEFONO VARCHAR2(9),
    CONSTRAINT CENTROS_ID_PK PRIMARY KEY (ID)
);

--PASOS COMPROBACIÓN DE TABLAS
-- 1.COMPROBAR QUE LA TABLA ESTE EN EL DICCIONARIO
DESC USER_TABLES

SELECT TABLE_NAME
FROM USER_TABLES
WHERE UPPER(TABLE_NAME)='CENTRO';

--2.COMPROBAR LAS COLUMNAS DE LA TABLA
DESC CENTRO

--PASO PARA COMPROBAR RESTRICCIONES
DESC USER_CONS_COLUMNS
DESC USER_CONSTRAINTS

SELECT C.CONSTRAINT_NAME, C.CONSTRAINT_TYPE, C.TABLE_NAME, CC.COLUMN_NAME, C.GENERATED
FROM USER_CONSTRAINTS C,USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME --JOIN
AND UPPER(C.TABLE_NAME)= 'CENTRO';

DESC USER_SEQUENCES
SELECT * FROM USER_SEQUENCES;

SELECT * FROM CENTRO;

--EJERCICIO 7
INSERT INTO CENTRO (NOMBRE, CALLE, NUMERO, CP, CIUDAD, PROVINCIA, TELEFONO)
VALUES ('ARRIAGA', 'POZOA KALEA', NULL, '01013', 'VITORIA-GASTEIZ', 'ALAVA', '945010110')
;

select table_name, column_name, data_default
from user_tab_columns
where upper(table_name)= 'CENTRO';

SELECT LAST_NUMBER, INCREMENT_BY, MIN_VALUE, MAX_VALUE
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = '';

--EJERCICIO 8
CREATE INDEX IND_FK_DEPT
ON EMPLE(DEPT_NO);

--EJERCICIO 9
DESC USER_INDEXES;
SELECT INDEX_NAME, INDEX_TYPE, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE UPPER(TABLE_NAME)= 'EMPLE';

--EJERCICIO 10
DROP INDEX IND_FK_DEPT;

--EJERCICIO 11
DESC DEPART

CREATE INDEX IND_DEPT_DNOMBRE
ON DEPART(DNOMBRE);

--EJERCICIO 13
ALTER INDEX IND_DEPT_DNOMBRE MONITORING USAGE;

--EJERCICIO 14


ALTER INDEX IND_DEPT_DNOMBRE NOMONITORING USAGE;

--EJERCICIO 15
CREATE PUBLIC SYNONYM DEP1
FOR DEPART;

ALTER TABLE DEPART RENAME DEPARTS;

DESC USER_SYNONYMS

SELECT SYNONYM_NAME, TABLE_NAME
FROM USER_SYSNONYMS
WHERE UPPER(SYNONYM_NAME)= 'DEP1';


--EJERCICIO 16
DROP SYNONYM DEP1;

