--EJERCICIO 1
DESC DEPART

DESC USER_CONSTRAINTS
DESC USER_CONS_COLUMNS

SELECT USER_CONSTRAINTS.CONSTRAINT_NAME, USER_CONS_COLUMNS.COLUMN_NAME
FROM USER_CONSTRAINTS, USER_CONS_COLUMNS
WHERE USER_CONSTRAINTS.CONSTRAINT_NAME = USER_CONS_COLUMNS.CONSTRAINT_NAME 
AND UPPER(USER_CONSTRAINTS.TABLE_NAME)= 'DEPART';

DROP TABLE DEPARTSEQ;

CREATE TABLE DEPARTSEQ AS SELECT * FROM DEPART;

DESC DEPARTSEQ;

SELECT * FROM DEPARTSEQ;

--EJERCICIO 2
DROP SEQUENCE DEPT_ID_SEQ;

CREATE SEQUENCE DEPT_ID_SEQ
START WITH 200
MAXVALUE 1000
INCREMENT BY 10
NOCYCLE
NOCACHE;

DESC USER_SEQUENCES;

SELECT * FROM USER_SEQUENCES
WHERE UPPER(SEQUENCE_NAME)= 'DEPT_ID_SEQ';

--EJERCICIO 3
DESC USER_SEQUENCES
SELECT SEQUENCE_NAME, MAX_VALUE, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES;

--EJERCICIO 4
/*ESTA EN EL SCRIPT LAB9_4.SQL*/

--EJERCICIO 5
SELECT DEPT_ID_SEQ.NEXTVAL 
FROM DUAL;

--AÑADIR UN NUEVO DEPARTAMENTO CON LA SECUENCIA RECIÉN GENERADA 
INSERT INTO DEPARTSEQ (DEPT_NO, DNOMBRE)
VALUES (DEPT_ID_SEQ.CURRVAL, 'MOLANO');

SELECT * 
FROM DEPARTSEQ
WHERE UPPER(DNOMBRE)='MOLANO';

ROLLBACK;

--COMPROBACIÓN DEL ROLLBACK
SELECT * 
FROM DEPARTSEQ;

--EJERCICIO 6
