--EJERCICIO 1

CREATE OR REPLACE VIEW DEPT_SUM AS( 
SELECT D.DNOMBRE "DEPT_NOMBRE" , MIN(E.SALARIO) "SAL_MIN" ,
MAX(E.SALARIO) "SAL_MAX" , TRUNC(AVG(E.SALARIO)) "SAL_MED"
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO=D.DEPT_NO --JOIN
GROUP BY E.DEPT_NO , D.DNOMBRE);
    
--COMPROBACION DE QUE SE HA CREADO LA VISTA

DESC DEPT_SUM;

SELECT VIEW_NAME , TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME)='DEPT_SUM';

--LA VISTA ES COMPLEJA. MÁS DE UNA TABLA, FUNCIONES DE GRUPO, ETC...

--EJERCICIO 2

DROP VIEW SAL_20;

--COMPROBACIÓN DE BORRADO

SELECT VIEW_NAME , TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME)='SAL_20';

--EJERCICIO 3

CREATE OR REPLACE VIEW DEPT_SALMAX AS 
(SELECT DEPT_NO "COD_DEPART" , TRUNC(MAX(SALARIO)) "SAL_MAX"
FROM EMPLE
GROUP BY DEPT_NO);
    
--COMPRUEBO QUE SE HA CREADO LA VISTA

DESC DEPT_SALMAX;

SELECT VIEW_NAME , TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME)='DEPT_SALMAX';

--EJERCICIO 4

SELECT E.APELLIDO , E.SALARIO , E.DEPT_NO "COD_DEPART"
FROM EMPLE E, DEPT_SUM DS, DEPART D
WHERE DS.DEPT_NOMBRE = D.DNOMBRE --JOIN DEPART Y VISTA
AND E.DEPT_NO = D.DEPT_NO -- JOIN EMPLE Y DEPART
AND E.SALARIO > DS.SAL_MED --CONDICION SALARIO MAYOR QUE LA MEDIA
ORDER BY E.APELLIDO;

--EJERCICIO 5
SELECT E.APELLIDO, E.SALARIO, E.DEPT_NO, DS.SAL_MED
FROM EMPLE E, DEPT_SUM DS, DEPART D
WHERE DS.DEPT_NOMBRE = D.DNOMBRE
AND E.DEPT_NO = D.DEPT_NO
AND E.SALARIO > DS.SAL_MED;

--EJERCICIO 6
CREATE OR REPLACE VIEW MP_MAX AS (
    SELECT E.APELLIDO, E.SALARIO, E.DEPT_NO, DSM.SAL_MAX
    FROM EMPLE E, (SELECT COD_DEPART, SAL_MAX
                    FROM DEPT_SALMAX) DSM
    WHERE DSM.COD_DEPART = E.DEPT_NO
    AND E.SALARIO < DSM.SAL_MAX
);

DESC MP_MAX

SELECT VIEW_NAME, TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME)= 'MP_MAX';

SELECT * 
FROM MP_MAX
ORDER BY APELLIDO;

--EJERCICIO 7
SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;



