CREATE OR REPLACE VIEW MP_MAX2 AS (
    SELECT E.APELLIDO, E.SALARIO, E.DEPT_NO, DSM.SAL_MAX
    FROM EMPLE E, (SELECT DEPT_NO, MAX(SALARIO) AS SAL_MAX
                    FROM EMPLE 
                    GROUP BY DEPT_NO) DSM
    WHERE DSM.DEPT_NO = E.DEPT_NO
    AND E.SALARIO < DSM.SAL_MAX
);

DESC MP_MAX2

SELECT VIEW_NAME, TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME)='MP_MAX2';

SELECT *
FROM MP_MAX2
ORDER BY APELLIDO;