--EJERCICIO 1
DESC DEPART

DESC USER_CONSTRAINTS
DESC USER_CONS_COLUMNS

SELECT USER_CONSTRAINTS.CONSTRAINT_NAME, USER_CONS_COLUMNS.COLUMN_NAME
FROM USER_CONSTRAINTS, USER_CONS_COLUMNS
WHERE USER_CONSTRAINTS.CONSTRAINT_NAME = USER_CONS_COLUMNS.CONSTRAINT_NAME 
AND UPPER(USER_CONSTRAINTS.TABLE_NAME)= 'DEPART';

CREATE TABLE DEPARTSEQ AS SELECT * FROM DEPART;

DESC DEPARTSEQ;

SELECT * FROM DEPARTSEQ;

--EJERCICIO 2
CREATE SEQUENCE DEPT_ID_SEQ
START WITH 200
MAXVALUE 1000
INCREMENT BY 10
NOCYCLE
NOCACHE;

DESC USER_SEQUENCES;

SELECT * FROM USER_SEQUENCES
WHERE UPPER(SEQUENCE_NAME)= 'DEPT_ID_SEQ';

