--EJERCICIO 3
ALTER TABLE TIENDAS ADD
(
    CONSTRAINT TIE_NOM_CK CHECK (NOMBRE = INITCAP(NOMBRE))
);
--EJERCICIO 4
DESC ALL_CONSTRAINTS;
DESC USER_CONSTRAINTS;

SELECT TABLE_NAME, OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, 
SEARCH_CONDITION
FROM USER_CONSTRAINTS 
WHERE UPPER(TABLE_NAME)IN ('TIENDAS','FABRICANTES','ARTICULOS','VENTAS','PEDIDOS');

--EJERCICIO 5
ALTER TABLE PEDIDOS MODIFY
(
    UNIDADES_PEDIDAS NUMBER(6)
);
ALTER TABLE VENTAS MODIFY
(
    UNIDADES_VENDIDAS NUMBER(6)
);

--EJERCICIO 6
ALTER TABLE TIENDAS ADD
(
    CONSTRAINT TIE_PRO_TOL_CK CHECK (UPPER(PROVINCIA) !='TOLEDO')
);
ALTER TABLE TIENDAS DROP CONSTRAINT TIE_PRO_TOL_CK;

--EJERCICIO 7
ALTER TABLE PEDIDOS ADD
(
    PVP NUMBER(4) DEFAULT 0
);
ALTER TABLE VENTAS ADD
(
    PVP NUMBER(4) DEFAULT 0
);

--EJERCICIO 8
ALTER TABLE PEDIDOS DROP COLUMN PVP;
ALTER TABLE VENTAS DROP COLUMN PVP;