--EJERCICIO 1
INSERT INTO DEPART(DEPT_NO,DNOMBRE,LOC)
VALUES (11,'CALIDAD','SANTANDER');
INSERT INTO EMPLE (EMP_NO,APELLIDO,OFICIO)
VALUES (7230,'AGUIRRE','EMPLEADO');
--EJERCICIO 2
UPDATE EMPLE SET SALARIO = SALARIO - 10%;