--EJERCICIO 1
DROP TABLE ALUMNOS
/

CREATE TABLE ALUMNOS (
    DNI VARCHAR2(10),
    NOMBRE VARCHAR2(30) NOT NULL,
    EDAD NUMBER(2),
    CURSO NUMBER(1),
    CONSTRAINT ALU_DNI_PK PRIMARY KEY (DNI),
    CONSTRAINT ALU_EDAD_MIN_CK CHECK (EDAD BETWEEN 5 AND 20),
    CONSTRAINT ALU_NOM_CK CHECK (NOMBRE = UPPER(NOMBRE)),
    CONSTRAINT ALU_CUR_CK CHECK (CURSO IN (1,2,3))  
);
--COMENTARIO DE LÍNEA
/*C
ASDF COMENTARIO DE BLOQUE*/

--EJERCICIO 2
ALTER TABLE ALUMNOS ADD (
    SEXO VARCHAR2(1) NOT NULL CONSTRAINT ALU_SEX_CK CHECK (SEXO IN('M','F')),
    IMPORTE NUMBER(10,2) DEFAULT 0
    );
    
--EJERCICIO 3    

ALTER TABLE ALUMNOS DROP (EDAD);
ALTER TABLE ALUMNOS ADD(
    FECHA_NAC DATE,
    FECHA_ALTA DATE
);

ALTER TABLE ALUMNOS ADD(
    CONSTRAINT ALU_FIA_CK CHECK (FECHA_NAC < FECHA_ALTA )
);
--ALTER TABLE ALUMNOS DROP (FECHA_NAC);
--HAY QUE BORRAR PRIMERO LA CONSTRAINT
ALTER TABLE ALUMNOS DROP (FECHA_NAC) CASCADE CONSTRAINT;

--EJERCICIO 4
ALTER TABLE ALUMNOS RENAME COLUMN IMPORTE TO TASAS;

--EJERCICIO 5
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='ALUMNOS';



