--EJERCICIO 6
DROP TABLE PROVINCIAS;
DROP TABLE PERSONAS;
CREATE TABLE PROVINCIAS(
    COD_PROV NUMBER(2),
    NOM_PROV VARCHAR2(15),
    CONSTRAINT PRO_COD_PK PRIMARY KEY (COD_PROV)
);

CREATE TABLE PERSONAS(
    DNI NUMBER(8),
    NOMBRE VARCHAR2(15),
    DIRECCION VARCHAR2(25),
    POBLACION VARCHAR2(20),
    COD_PROV NUMBER(2),
    CONSTRAINT PER_DNI_PK PRIMARY KEY (DNI),
    CONSTRAINT PER_COD_FK FOREIGN KEY (COD_PROV) REFERENCES PROVINCIAS 
);
--EJERCICIO 7
ALTER TABLE PERSONAS RENAME TO CUIDADANOS;
DESC CUIDADANOS;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME=('PROVINCIAS');
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME=('CUIDADANOS');

--EJERCICIO 8
DROP TABLE PROVINCIAS;
--NO
--SI, INFLUYE PORQUE CUANDO ES UNA CLAVE FORANEA EN OTRO SITIO NO DEJA BORRARLO

