--EJERCICIO 1
SELECT E.APELLIDO,E.OFICIO,D.DNOMBRE,D.LOC
FROM EMPLE E,DEPART D
WHERE E.DEPT_NO = D.DEPT_NO;

--EJERCICIO 2
SELECT E.EMP_NO, E.APELLIDO, E.OFICIO, E.ID_JEFE, E.FECHA_ALTA, E.SALARIO, E.COMISION_PCT, E.DEPT_NO, D.LOC
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
AND UPPER(D.LOC)IN('BARCELONA','MADRID');

--EJERCICIO 3
SELECT ID_JEFE, OFICIO
FROM EMPLE;


SELECT E.EMP_NO, E.APELLIDO, E.ID_JEFE, J.APELLIDO AS "APELLIDO DEL JEFE", J.EMP_NO AS "CODIGO JEFE"
FROM EMPLE E, EMPLE J
WHERE E.ID_JEFE = J.EMP_NO;

--EJERCICIO 4
SELECT E.APELLIDO, E.OFICIO, D.LOC
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
AND UPPER(E.OFICIO) = 'ANALISTA';

--EJERCICIO 5
SELECT E.EMP_NO, E.APELLIDO, E.ID_JEFE,NVL(J.APELLIDO, 'NO TIENE JEFE') AS "APELLIDO DEL JEFE", J.EMP_NO AS "CODIGO JEFE"
FROM EMPLE E, EMPLE J
WHERE E.ID_JEFE = J.EMP_NO(+);

--EJERCICIO 6

SELECT E.APELLIDO, D.DNOMBRE, E.DEPT_NO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO(+) = D.DEPT_NO;

--SI QUISIESEMOS SACAR UN CODIGO EN LA FILA DE DEPT_NO

SELECT E.APELLIDO, D.DNOMBRE, D.DEPT_NO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO(+) = D.DEPT_NO;


