--EJERCICIO 1
/*1. Obtener el apellido 
de los empleados que tienen el mismo oficio que ‘GIL’.*/

SELECT OFICIO, APELLIDO
FROM EMPLE
WHERE UPPER(APELLIDO) = 'GIL';

SELECT APELLIDO
FROM EMPLE
WHERE OFICIO IN (SELECT DISTINCT OFICIO
                FROM EMPLE
                WHERE UPPER(APELLIDO) = 'GIL')
AND UPPER(APELLIDO)!= 'GIL';
                
--EJERCICIO 2
/*2. Queremos consultar los datos de los empleados 
que trabajan en las localidades de ‘MADRID’ o ‘BARCELONA’.*/
SELECT E.EMP_NO, E.APELLIDO, E.OFICIO, E.ID_JEFE, E.FECHA_ALTA, 
E.SALARIO, E.COMISION_PCT, E.DEPT_NO, D.LOC
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO --JOIN
AND UPPER(D.LOC) IN ('BARCELONA', 'MADRID');
 
--ESTA SOLUCIÓN NO SERVIRIA SI NOS OBLIGAN A SACAR EL NOMBRE DE LA LOCALIDAD. 
SELECT E.EMP_NO, E.APELLIDO, E.OFICIO, E.ID_JEFE, E.FECHA_ALTA, 
E.SALARIO, E.COMISION_PCT, E.DEPT_NO
FROM EMPLE E
WHERE E.DEPT_NO IN (SELECT D.DEPT_NO
                    FROM DEPART D
                    WHERE UPPER(LOC) IN ('BARCELONA', 'MADRID'));                
--EJERCICIO 3
/*OBTENER EL APELLIDO DE LOS EMPLEADOS 
CON EL MISMO OFICIO Y SALARIO QUE 'GIL'*/
SELECT APELLIDO, OFICIO, SALARIO
FROM EMPLE
WHERE (OFICIO,SALARIO) IN (SELECT OFICIO, SALARIO
                FROM EMPLE
                WHERE UPPER(APELLIDO) = 'GIL')
AND UPPER(APELLIDO)!= 'GIL';

SELECT APELLIDO, OFICIO, SALARIO
FROM EMPLE
WHERE OFICIO IN (SELECT OFICIO
                FROM EMPLE
                WHERE UPPER(APELLIDO) = 'GIL')
AND SALARIO IN (SELECT SALARIO
                FROM EMPLE
                WHERE UPPER(APELLIDO)= 'GIL')
AND UPPER(APELLIDO)!= 'GIL';
                
--EJERCICIO 4
SELECT APELLIDO, OFICIO, SALARIO, FECHA_ALTA
FROM EMPLE
WHERE (OFICIO =ANY (SELECT DISTINCT OFICIO
                    FROM EMPLE
                    WHERE UPPER(APELLIDO)= 'JIMENEZ')
OR SALARIO >ALL (SELECT DISTINCT SALARIO
                    FROM EMPLE
                    WHERE UPPER(APELLIDO)= 'FERNANDEZ'))
AND UPPER(APELLIDO) NOT IN ('JIMENEZ','FERNANDEZ');                
                
                
--EJERCICIO 5
SELECT DEPT_NO, COUNT(EMP_NO)
FROM EMPLE 
GROUP BY DEPT_NO 
HAVING COUNT(EMP_NO) = (SELECT MAX(COUNT(*))
                        FROM EMPLE
                        GROUP BY DEPT_NO);

--EJERCICIO 6
SELECT OFICIO, AVG(SALARIO)
FROM EMPLE 
GROUP BY OFICIO
HAVING AVG(SALARIO) = (SELECT MIN(AVG(SALARIO))
                        FROM EMPLE
                        GROUP BY OFICIO);

SELECT OFICIO, AVG(SALARIO)
FROM EMPLE 
GROUP BY OFICIO
HAVING AVG(SALARIO) IN (SELECT MIN(SALARIO)
                        FROM EMPLE
                        GROUP BY OFICIO);

--EJERCICIO 7
SELECT EMP_NO, APELLIDO
FROM EMPLE
WHERE SALARIO = ( SELECT MIN(SALARIO))
				FROM EMPLE
				GROUP BY DEPT_NO);
                
--EJERCICIO 8
SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE OFICIO = ( SELECT OFICIO
			FROM EMPLE
			WHERE UPPER(APELLIDO) = 'PEREZ');
            
--EJERCICIO 9
SELECT APELLIDO
FROM EMPLE
WHERE ID_JEFE IS NULL;

--EJERCICIO 10
SELECT APELLIDO
FROM EMPLE
WHERE ID_JEFE IS NOT NULL;

--EJERCICIO 11
SELECT DISTINCT(DEPT_NO)
FROM EMPLE
WHERE UPPER(APELLIDO) LIKE '%A%';
                
SELECT EMP_NO, APELLIDO
FROM EMPLE 
WHERE DEPT_NO IN (SELECT DEPT_NO
                FROM EMPLE
                WHERE UPPER(APELLIDO) LIKE '%A%');
                
--EJERCICIO 12
SELECT EMP_NO, APELLIDO
FROM EMPLE 
WHERE DEPT_NO IN (SELECT DEPT_NO
                FROM EMPLE
                WHERE UPPER(APELLIDO) LIKE '%A%')
AND SALARIO = (SELECT AVG(SALARIO)
                FROM EMPLE
                WHERE );
--EJERCICIO 13
SELECT APELLIDO, DEPT_NO, SALARIO
FROM EMPLE 
WHERE (DEPT_NO, SALARIO) IN (SELECT DEPT_NO, SALARIO
                            FROM EMPLE
                            WHERE COMISION_PCT IS NOT NULL);

--EJERCICIO 14
SELECT APELLIDO, SALARIO, DEPT_NO
FROM EMPLE
WHERE ;
