--EJERCICIO 1
SELECT DISTINCT E.OFICIO, D.LOC
FROM EMPLE E, DEPART D 
WHERE E.DEPT_NO = D.DEPT_NO
AND E.DEPT_NO = 10; 


--EJERCICIO 2
SELECT D.DEPT_NO, D.DNOMBRE, COUNT(E.EMP_NO) AS "NUMERO DE EMPLEADOS"
FROM  DEPART D, EMPLE E
WHERE D.DEPT_NO = E.DEPT_NO(+)
GROUP BY D.DEPT_NO, D.DNOMBRE
ORDER BY D.DEPT_NO;

--EJERCICIO 3
SELECT E.DEPT_NO,D.DNOMBRE, COUNT(E.EMP_NO) AS "NÚMERO DE EMPLEADOS" 
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO --JOIN
GROUP BY E.DEPT_NO, D.DNOMBRE --QUEREMOS AGRUPARLO POR DEPARTAMENTOS NO POR EMPLEADOS
HAVING COUNT(E.EMP_NO) = (SELECT MAX(COUNT(EMP_NO))
                        FROM EMPLE
                        GROUP BY DEPT_NO);

--EJERCICIO 4
SELECT E.APELLIDO, D.DNOMBRE, E.SALARIO, E.COMISION_PCT
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
AND (E.SALARIO, E.COMISION_PCT) IN (SELECT E.SALARIO, E.COMISION_PCT
                                    FROM EMPLE E, DEPART D
                                    WHERE E.DEPT_NO = D.DEPT_NO
                                    AND UPPER(D.LOC)= 'BARCELONA')
AND UPPER(D.LOC)!= 'BARCELONA';
                
SELECT E.APELLIDO, D.DNOMBRE, E.SALARIO, E.COMISION_PCT
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
AND (E.SALARIO, E.COMISION_PCT) IN (SELECT E.SALARIO, E.COMISION_PCT
                                    FROM EMPLE E, DEPART D
                                    WHERE E.DEPT_NO = (SELECT DEPT_NO
                                                        FROM DEPART
                                                        WHERE UPPER(LOC)='BARCELONA'))
AND UPPER(D.LOC)!= 'BARCELONA';

--EMPLEADOS QUE NO TIENEN COMISION
--AQUELLOS QUE TIENEN COMISION NULA NO APARECEN
SELECT E.APELLIDO, D.DNOMBRE, E.SALARIO, NVL(TO_CHAR(E.COMISION_PCT), 'SIN COMISION')
-- EL TO_CHAR SIEMPRE EN ESTA FILA NO SE PUEDE PONER MÁS ABAJO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
AND (E.SALARIO, NVL(E.COMISION_PCT,-1)) IN (SELECT E.SALARIO, NVL(E.COMISION_PCT,-1)
                                            FROM EMPLE E, DEPART D
                                            WHERE E.DEPT_NO = D.DEPT_NO
                                            AND UPPER(LOC)='BARCELONA')
AND UPPER(D.LOC)!= 'BARCELONA';


