--EJERCICIO 1
SELECT EMP_NO, APELLIDO, OFICIO, ID_JEFE, FECHA_ALTA, SALARIO, COMISION_PCT, DEPT_NO
FROM EMPLE
WHERE SALARIO > (SELECT AVG(SALARIO)
                FROM EMPLE);
                
--EJERCICIO 2
SELECT E.APELLIDO, E.SALARIO, E.DEPT_NO
FROM EMPLE E
WHERE SALARIO > (SELECT AVG(SALARIO)
                FROM EMPLE
                WHERE DEPT_NO = E.DEPT_NO); 
                
--EJERCICIO 3
SELECT LOC, DNOMBRE
FROM DEPART D
WHERE EXISTS (SELECT DEPT_NO
                FROM EMPLE
                WHERE COMISION_PCT > SALARIO *0.10
                AND DEPT_NO = D.DEPT_NO);
                
--EJERCICIO 4
SELECT E.APELLIDO
FROM EMPLE E
WHERE 1 <= (SELECT COUNT(*)
            FROM EMPLE C
            WHERE E.DEPT_NO = C.DEPT_NO --QUITAR FILAS PARA QUEDARME CON LAS DE SU DPTO
            AND C.FECHA_ALTA > E.FECHA_ALTA
            AND C.SALARIO > E.SALARIO);

SELECT APELLIDO
FROM EMPLE E
WHERE EXISTS (SELECT 'X'
                FROM EMPLE C
                WHERE E.DEPT_NO = C.DEPT_NO --CORRELACIONAR
                AND C.FECHA_ALTA > E.FECHA_ALTA
                AND C.SALARIO > E.SALARIO);


--EJERCICIO 5
SELECT DEPT_NO
FROM DEPART D
WHERE NOT EXISTS (SELECT 'X'
                    FROM EMPLE
                    WHERE DEPT_NO = D.DEPT_NO);
/*OTRA FORMA
LA MISMA SUBCONSULTA PODEMOS EXPRESARLA CON EL OPERADOR NOT IN DE LA SIGUIENTE MANERA*/                    
SELECT DEPT_NO
FROM DEPART 
WHERE DEPT_NO NOT IN (SELECT DISTINCT DEPT_NO
                    FROM EMPLE);                