/*ESPECIALISTA C*/



/*ESPECIALISTA D*/
--EJERCICIO 5
--5.1
SELECT EMP_NO, APELLIDO
FROM EMPLE
WHERE UPPER(APELLIDO) LIKE('A%O');

--5.2
SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE UPPER(APELLIDO) NOT IN('VENDEDOR','ANALISTA','EMPLEADO');

--5.3
SELECT EMP_NO, APELLIDO, COMISION_PCT
FROM EMPLE
WHERE UPPER(COMISION_PCT) IS NOT NULL;

--5.4
SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE UPPER(OFICIO)= 'ANALISTA'
ORDER BY EMP_NO;

SELECT * FROM EMPLE;