--EJERCICIO 1
SELECT AVG(SALARIO) AS MEDIA, MAX(SALARIO) AS "SALARIO MAXIMO", MIN(SALARIO) AS "SALARIO MINIMO", SUM(SALARIO)
FROM EMPLE
WHERE UPPER(OFICIO) = 'COMERCIAL';

--EJERCICIO 2
SELECT MIN(TO_CHAR(FECHA_ALTA)) AS "MAYOR ANTIGUEDAD", MAX(TO_CHAR(FECHA_ALTA)) AS "MENOR ANTIGUEDAD"
FROM EMPLE;

--EJERCICIO 3
SELECT EMP_NO,APELLIDO
FROM EMPLE
ORDER BY APELLIDO ASC;

SELECT MIN(APELLIDO) AS "PRIMER APELLIDO", MAX(APELLIDO) AS "ULTIMO APELLIDO"
FROM EMPLE;

--EJERCICIO 4
SELECT EMP_NO,DEPT_NO
FROM EMPLE;

SELECT COUNT(*)
FROM EMPLE
WHERE DEPT_NO = 40;

--EJERCICIO 5
SELECT EMP_NO, COMISION_PCT
FROM EMPLE;

SELECT COUNT(*)
FROM EMPLE
WHERE DEPT_NO = 30
AND COMISION_PCT IS NOT NULL;

--EJERCICIO 6
SELECT EMP_NO, DEPT_NO
FROM EMPLE;

SELECT COUNT(DISTINCT(DEPT_NO))
FROM EMPLE;
--EJERCICIO 7
SELECT COUNT(DEPT_NO) AS "Nº EMPLEADOS", DEPT_NO AS "Nº DEPARTAMENTO"
FROM EMPLE
GROUP BY DEPT_NO;

--EJERCICIO 8
SELECT COUNT(DEPT_NO) AS "Nº EMPLEADOS", DEPT_NO AS "Nº DEPARTAMENTO"
FROM EMPLE
GROUP BY DEPT_NO; 