--EJERCICIO 1
SELECT DEPT_NO, COUNT(*) AS "EMPLEADOS POR DEPT"
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(*)> 4
ORDER BY COUNT(*) DESC;

--EJERCICIO 2
SELECT DEPT_NO, SUM(SALARIO) AS "SUMA DE LOS SALARIOS", MAX(SALARIO) AS "SALARIO MAXIMO", MIN(SALARIO) AS "SALARIO MINIMO"
FROM EMPLE
GROUP BY DEPT_NO
ORDER BY DEPT_NO ASC;