/*ESPECIALISTA A*/

/*ESPECIALISTA C*/
--EJERCICIO 4
--4.1
SELECT EMP_NO, APELLIDO
FROM EMPLE
WHERE UPPER(APELLIDO) LIKE ('_R%');

--4.2
SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE UPPER(APELLIDO) NOT IN('VENDEDOR','ANALISTA','EMPLEADO');

--4.3
SELECT EMP_NO, APELLIDO, COMISION_PCT
FROM EMPLE
WHERE COMISION_PCT IS NULL;

--4.4
SELECT EMP_NO, DEPT_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE DEPT_NO = 20
ORDER BY APELLIDO, SALARIO;

/*ESPECIALISTA D*/
--EJERCICIO 5
--5.1
SELECT EMP_NO, APELLIDO
FROM EMPLE
WHERE UPPER(APELLIDO) LIKE('A%O');

--5.2
SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE UPPER(APELLIDO) NOT IN('VENDEDOR','ANALISTA','EMPLEADO');

--5.3
SELECT EMP_NO, APELLIDO, COMISION_PCT
FROM EMPLE
WHERE UPPER(COMISION_PCT) IS NOT NULL;

--5.4
SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE UPPER(OFICIO)= 'ANALISTA'
ORDER BY EMP_NO;

SELECT * FROM EMPLE;