--EJERCICIO 1
SELECT EMP_NO, APELLIDO
FROM EMPLE
WHERE ID_JEFE IS NULL;


SELECT APELLIDO AS "EMPLEADO", NVL(TO_CHAR(ID_JEFE), 'NO TIENE JEFE') AS "JEFE"
FROM EMPLE
ORDER BY ID_JEFE DESC;

--EJERCICIO 2
SELECT EMP_NO, SALARIO
FROM EMPLE;

SELECT EMP_NO || ',' || APELLIDO AS "EMPLEADO", SALARIO, TRUNC(SALARIO/1000,0) AS "PORCENTAJE DE MOVILIZACION"
FROM EMPLE;
/*EL 0 INDICA LA CANTIDAD DE DECIMALES QUE QUEREMOS*/

--EJERCICIO 3
SELECT EMP_NO AS "CODIGO EMPLEADO", APELLIDO, OFICIO, SUBSTR(INITCAP(APELLIDO),0,3) || LENGTH(APELLIDO) ||LOWER(OFICIO)
        AS "NOMBRE DE USUARIO", EXTRACT(MONTH FROM FECHA_ALTA) || SUBSTR(EXTRACT(YEAR FROM FECHA_ALTA),2,2) ||
        REVERSE(SUBSTR(REVERSE(APELLIDO),1,2)) AS "CLAVE"
FROM EMPLE
ORDER BY APELLIDO;

--EJERCICIO 4
SELECT EMP_NO AS "CODIGO EMPLEADO", APELLIDO, TO_CHAR(SALARIO,'999,999.999')AS "SALARIO ACTUAL", 
    SALARIO + SUBSTR(SALARIO,1,1)/100 AS "PORCENTAJE DE AUMENTO",
    TO_CHAR(SALARIO * SUBSTR(SALARIO,1,1)/100 + SALARIO, '999,999.999') AS "SALARIO NUEVO" 
FROM EMPLE;

--EJERCICIO 5
SELECT EMP_NO AS "ID_EMP", SALARIO AS "SALARIO ACTUAL", 
    NVL(TO_CHAR(COMISION_PCT),'SIN COMISION') AS "PORCENTAJE COMISION",
    NVL(SALARIO*COMISION_PCT/100,0) AS "COMISION", 
    NVL(SALARIO+SALARIO*COMISION_PCT/100,SALARIO) AS "SALARIO TOTAL CALCULADO"
FROM EMPLE;

SELECT NVL2(COMISION_PCT, SALARIO * COMISION_PCT/100,0) AS COMISION
FROM EMPLE;

SELECT EMPLE.SALARIO, 
NVL2(EMPLE.COMISION_PCT, EMPLE.SALARIO + EMPLE.SALARIO * EMPLE.COMISION_PCT/100,EMPLE.SALARIO) AS "SALARIO CALCULADO",
DEPART.DNOMBRE
FROM EMPLE,DEPART
WHERE EMPLE.DEPT_NO = DEPART.DEPT_NO /*CONDICION PARA CONSEGUIR LA JOIN*/
;


/*ADEMAS QUEREMOS SABER EL NOMBRE DEL DEPARTAMENTO*/
--EJERCICIO 6
SELECT EMP_NO, FECHA_ALTA, ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_ALTA))