DECLARE
    V_EMP_NO EMPLE.EMP_NO%TYPE;
    V_APELLIDO EMPLE.APELLIDO%TYPE;
 
BEGIN
   SELECT EMP_NO, APELLIDO
   INTO V_EMP_NO, V_APELLIDO
   FROM EMPLE;
EXCEPTION
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('TENGO DEMASIADOS VALORES');
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO TENGO NINGUNA FILA');
END ;